# -*- coding: utf-8 -*-
"""Acompanhamento Faturamento Exportação base historico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkmNVmBtnsfu_BwRBIAy7RSh7Nvc72Ty
"""

# ==================================================================
# RELATÓRIO COMPARATIVO ÁGUA / ESGOTO — GERAÇÃO AUTOMÁTICA
# ==================================================================
import pandas as pd
import numpy as np
import glob
import os
import io
import re
import html
from tqdm.auto import tqdm

# ==================================================================
# CONFIGURAÇÃO GERAL — CAMINHOS E CONSTANTES
# ==================================================================
# ------------------------------------------------------------------
# ORIGEM DOS ARQUIVOS — escolha como o script vai buscar os arquivos
#   "upload" → (Colab) botão para escolher os arquivos do seu computador
#   "drive"  → (Colab) usa uma pasta do Google Drive (ideal com o
#              Google Drive para desktop sincronizando uma pasta do PC)
#   "local"  → (rodando no PC: VS Code, Jupyter, Spyder) abre a janela
#              do Windows para selecionar a pasta
# ------------------------------------------------------------------
MODO_ORIGEM          = "upload"
PASTA_DRIVE          = "/content/drive/MyDrive/Faturamento"   # usado só no modo "drive"
LIMPAR_PASTA_ANTES   = True   # (upload) apaga arquivos antigos para não misturar meses

EXTENSOES_VALIDAS = (".csv", ".xlsx", ".xls")

def em_colab():
    try:
        import google.colab  # noqa: F401
        return True
    except ImportError:
        return False

def seleciona_pasta_local():
    """Abre a janela do sistema para escolher a pasta (execução no PC)."""
    import tkinter as tk
    from tkinter import filedialog
    root = tk.Tk()
    root.withdraw()
    root.attributes("-topmost", True)
    pasta = filedialog.askdirectory(
        title="Selecione a pasta com os arquivos de consumo, fatura e cronograma"
    )
    root.destroy()
    if not pasta:
        raise SystemExit("❌ Nenhuma pasta selecionada. Execução cancelada.")
    return pasta

def envia_arquivos_colab(destino):
    """Mostra o botão 'Escolher arquivos' e copia o que foi enviado para a pasta de trabalho."""
    from google.colab import files
    os.makedirs(destino, exist_ok=True)
    if LIMPAR_PASTA_ANTES:
        for arq in os.listdir(destino):
            caminho = os.path.join(destino, arq)
            if os.path.isfile(caminho):
                os.remove(caminho)
    print("📤 Clique em 'Escolher arquivos', abra a pasta do seu computador")
    print("   e selecione TODOS os arquivos (Ctrl+A) → Abrir.\n")
    enviados = files.upload()
    if not enviados:
        raise SystemExit("❌ Nenhum arquivo enviado. Execução cancelada.")
    for nome, conteudo in enviados.items():
        if not nome.lower().endswith(EXTENSOES_VALIDAS):
            print(f"   ⚠️ Ignorado (extensão não suportada): {nome}")
        else:
            with open(os.path.join(destino, nome), "wb") as f:
                f.write(conteudo)
            print(f"   ✅ {nome}")
        # files.upload() também grava no diretório atual — remove a cópia extra
        copia_extra = os.path.join(os.getcwd(), nome)
        if os.path.abspath(copia_extra) != os.path.abspath(os.path.join(destino, nome)) and os.path.exists(copia_extra):
            os.remove(copia_extra)
    return destino

def define_pasta_arquivos():
    # Pasta definida de fora (ex.: o site no navegador ou um agendador)
    pasta_externa = os.environ.get("FATURAMENTO_PASTA")
    if pasta_externa:
        pasta = pasta_externa
    elif MODO_ORIGEM == "local" or not em_colab():
        pasta = seleciona_pasta_local()
    elif MODO_ORIGEM == "drive":
        from google.colab import drive
        drive.mount("/content/drive")
        pasta = PASTA_DRIVE
        if not os.path.isdir(pasta):
            raise FileNotFoundError(f"Pasta não encontrada no Drive: {pasta}")
    else:
        pasta = envia_arquivos_colab("/content/Arquivo")
    print(f"📂 Pasta de trabalho: {pasta}\n")
    return pasta

PASTA_ARQUIVOS       = define_pasta_arquivos()
CAMINHO_SAIDA        = os.path.join(PASTA_ARQUIVOS, "Base_Compilada_HISTORICO.xlsx")
CAMINHO_SAIDA_HTML   = os.path.join(PASTA_ARQUIVOS, "Relatorio_Comparativo.html")
CAMINHO_SAIDA_TOP100 = os.path.join(PASTA_ARQUIVOS, "Top100_Quedas_Consumo.xlsx")

os.makedirs(PASTA_ARQUIVOS, exist_ok=True)

col_economias = [
    "Qtd. Economia Residencial",
    "Qtd. Economia Comercial",
    "Qtd. Economia Industrial",
    "Qtd. Economia Publica",
    "Qtd. Economia Outros"
]

COLUNAS_CONSUMO    = {"Leitura Atual", "Consumo Medido", "Consumo Faturado"}
COLUNAS_FATURA     = {"Rubrica", "Valor Parcela", "Data de Vencimento"}
COLUNAS_CRONOGRAMA = {"Grupo", "Data da Leitura", "Qts. Dias"}

MESES_PT = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho",
            "Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"]

# ==================================================================
# BARRA DE PROGRESSO GERAL (0% a 100%)
# ==================================================================
barra_progresso = tqdm(
    total=100,
    desc="Iniciando",
    unit="%",
    bar_format="{l_bar}{bar}| {n:.0f}%"
)

def atualiza_progresso(percentual, descricao):
    percentual = max(0, min(100, float(percentual)))
    barra_progresso.set_description_str(descricao)
    incremento = percentual - barra_progresso.n
    if incremento > 0:
        barra_progresso.update(incremento)

def progresso_da_etapa(indice, total, inicio, fim, descricao):
    if total <= 0:
        atualiza_progresso(fim, descricao)
        return
    percentual = inicio + (fim - inicio) * indice / total
    atualiza_progresso(percentual, descricao)

# ==================================================================
# FUNÇÕES DE LEITURA E CLASSIFICAÇÃO DE ARQUIVOS
# ==================================================================

def detecta_linha_cabecalho(caminho, sheet_name=0, max_linhas=10):
    ext = os.path.splitext(caminho)[1].lower()
    try:
        if ext in (".xlsx", ".xls"):
            df_raw = pd.read_excel(caminho, sheet_name=sheet_name, header=None,
                                    dtype=str, nrows=max_linhas)
        else:
            with open(caminho, "rb") as f_bytes:
                raw = f_bytes.read()
                try:
                    content = raw.decode("utf-8-sig")
                except UnicodeDecodeError:
                    content = raw.decode("latin-1")
            df_raw = pd.read_csv(io.StringIO(content), sep=";", header=None,
                                  dtype=str, nrows=max_linhas)
    except:
        return None
    todas_colunas_possiveis = COLUNAS_CONSUMO | COLUNAS_FATURA | COLUNAS_CRONOGRAMA
    for i in range(len(df_raw)):
        valores_linha = set(str(v).strip() for v in df_raw.iloc[i].tolist())
        if len(valores_linha & todas_colunas_possiveis) >= 2:
            return i
    return None

def le_dataframe(caminho, nrows=None, sheet_name=0):
    ext = os.path.splitext(caminho)[1].lower()
    linha_header = detecta_linha_cabecalho(caminho, sheet_name=sheet_name)
    if linha_header is None:
        linha_header = 0
    if ext == ".csv":
        with open(caminho, "rb") as f_bytes:
            raw = f_bytes.read()
            try:
                content = raw.decode("utf-8-sig")
            except:
                content = raw.decode("latin-1")
        f = io.StringIO(content)
        primeira_linha = f.readline()
        skip = linha_header
        if primeira_linha.strip().lower().startswith("sep="):
            skip += 1
        f.seek(0)
        df = pd.read_csv(f, sep=";", skiprows=skip, dtype=str)
    elif ext in (".xlsx", ".xls"):
        df = pd.read_excel(caminho, dtype=str, header=linha_header)
    else:
        return None
    df.columns = df.columns.astype(str).str.strip().str.replace('"', '').str.replace('ï»¿', '')
    df.columns = [c.replace("P?blica", "Publica").replace("Pública", "Publica") for c in df.columns]
    return df

def identifica_tipo(colunas):
    colunas = set(colunas)
    if COLUNAS_CONSUMO.issubset(colunas):
        return "consumo"
    if COLUNAS_FATURA.issubset(colunas):
        return "fatura"
    if COLUNAS_CRONOGRAMA.issubset(colunas):
        return "cronograma"
    return "desconhecido"

def padroniza_referencia(serie):
    serie = serie.astype(str).str.strip()
    dt_completa = pd.to_datetime(serie, format="%d/%m/%Y", errors="coerce")
    faltantes = dt_completa.isna()
    if faltantes.any():
        dt_mes = pd.to_datetime(serie[faltantes], format="%m/%Y", errors="coerce")
        dt_completa.loc[faltantes] = dt_mes
    return dt_completa.dt.strftime("%m/%Y")

# ------------------------------------------------------------------
# PROCESSAMENTO — ARQUIVO DE CONSUMO
# ------------------------------------------------------------------
def processa_consumo(caminho):
    print(f"   ⚙️ Processando CONSUMO: {os.path.basename(caminho)}")
    df = le_dataframe(caminho)

    possiveis_nomes_ligacao = ["N. Ligacao", "N. da Ligacao", "N Ligacao", "N. da Ligação", "N. Ligação"]
    col_ligacao = next((c for c in possiveis_nomes_ligacao if c in df.columns), None)
    if col_ligacao is None:
        raise KeyError(
            f"Coluna de nº de ligação não encontrada no arquivo de CONSUMO "
            f"{os.path.basename(caminho)}. Colunas disponíveis: {list(df.columns)}"
        )

    for c in ["Leitura Atual", "Consumo Medido", "Consumo Faturado"] + col_economias:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0)

    df["Total Economias"] = df[col_economias].sum(axis=1)
    df["Qtd. Tipos de Economia"] = (df[col_economias] > 0).sum(axis=1)
    df["Economia Mista"] = df["Qtd. Tipos de Economia"].apply(lambda x: "Sim" if x > 1 else "Não")
    nome_arquivo = os.path.basename(caminho)
    match = re.search(r"(\d{2})[-/](\d{4})", nome_arquivo)
    df["Referência"] = f"{match.group(1)}/{match.group(2)}" if match else np.nan

    df["N. Ligação_consumo"] = df[col_ligacao].astype(str).str.strip()

    colunas_conflito = ["Grupo", "Situacao Ligacao", "Nome Cliente", "Categoria", col_ligacao]
    df = df.drop(columns=[c for c in colunas_conflito if c in df.columns], errors="ignore")

    return df.drop_duplicates(subset=["N. Ligação_consumo", "Referência"])

# ------------------------------------------------------------------
# PROCESSAMENTO — ARQUIVO DE FATURA
# ------------------------------------------------------------------
def processa_fatura(caminho):
    print(f"   ⚙️ Processando FATURA: {os.path.basename(caminho)}")
    df = le_dataframe(caminho)

    possiveis_nomes_ligacao = ["N. Ligacao", "N. da Ligacao", "N Ligacao", "N. da Ligação", "N. Ligação"]
    col_ligacao = next((c for c in possiveis_nomes_ligacao if c in df.columns), None)
    if col_ligacao is None:
        raise KeyError(
            f"Coluna de nº de ligação não encontrada no arquivo de FATURA "
            f"{os.path.basename(caminho)}. Colunas disponíveis: {list(df.columns)}"
        )

    df["N. da Ligacao"] = df[col_ligacao].astype(str).str.strip()

    df["Valor Parcela"] = (
        df["Valor Parcela"]
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
        .astype(float)
    )
    rubricas_validas = ["VALOR DE AGUA", "VALOR DE ESGOTO"]
    df_filter = df[df["Rubrica"].isin(rubricas_validas)].copy()
    df_filter["Grupo"] = df_filter["Grupo"].astype(str).str.strip()
    df_filter["Referencia de Leitura"] = padroniza_referencia(df_filter["Referencia de Leitura"])
    return df_filter

# ------------------------------------------------------------------
# PROCESSAMENTO — ARQUIVO DE CRONOGRAMA
# ------------------------------------------------------------------
def processa_cronograma(caminho):
    print(f"   ⚙️ Processando CRONOGRAMA: {os.path.basename(caminho)}")
    ext = os.path.splitext(caminho)[1].lower()
    frames = []
    if ext in (".xlsx", ".xls"):
        try:
            abas = pd.ExcelFile(caminho).sheet_names
        except:
            return pd.DataFrame()
        for aba in abas:
            try:
                df = le_dataframe(caminho, sheet_name=aba)
                if df is not None and COLUNAS_CRONOGRAMA.issubset(set(df.columns)):
                    df["Aba/Mês Cronograma"] = str(aba)
                    frames.append(df)
            except:
                continue
    else:
        df = le_dataframe(caminho)
        if df is not None and COLUNAS_CRONOGRAMA.issubset(set(df.columns)):
            df["Aba/Mês Cronograma"] = os.path.basename(caminho)
            frames.append(df)
    if not frames:
        return pd.DataFrame(columns=["Grupo", "Data da Leitura", "Qts. Dias", "Aba/Mês Cronograma"])
    df_final = pd.concat(frames, ignore_index=True)
    df_final["Grupo"] = df_final["Grupo"].astype(str).str.strip()
    df_final = df_final[df_final["Grupo"] != ""]
    df_final["Qts. Dias"] = pd.to_numeric(df_final["Qts. Dias"], errors="coerce")
    return df_final.drop_duplicates(subset=["Grupo", "Aba/Mês Cronograma"])

# ==================================================================
# ETAPA 1/6 — VARREDURA E CLASSIFICAÇÃO DOS ARQUIVOS DA PASTA
# ==================================================================
print("="*70)
print("ETAPA 1/6 — VARREDURA E CLASSIFICAÇÃO DOS ARQUIVOS")
print("="*70)

arquivos_saida = {
    os.path.abspath(CAMINHO_SAIDA),
    os.path.abspath(CAMINHO_SAIDA_HTML),
    os.path.abspath(CAMINHO_SAIDA_TOP100),
}
arquivos_raw = (
    glob.glob(os.path.join(PASTA_ARQUIVOS, "*.csv"))
    + glob.glob(os.path.join(PASTA_ARQUIVOS, "*.xlsx"))
    + glob.glob(os.path.join(PASTA_ARQUIVOS, "*.xls"))
)
arquivos = [c for c in arquivos_raw if os.path.abspath(c) not in arquivos_saida]
print(f"🔍 {len(arquivos)} arquivo(s) encontrado(s) em: {PASTA_ARQUIVOS}\n")

classificados = []
total_arquivos = len(arquivos)
atualiza_progresso(2, "Varrendo arquivos")
if total_arquivos == 0:
    atualiza_progresso(18, "Nenhum arquivo")
    raise FileNotFoundError(f"Nenhum arquivo CSV/XLSX/XLS em {PASTA_ARQUIVOS}")

for idx, caminho in enumerate(arquivos, start=1):
    nome = os.path.basename(caminho)
    try:
        ext = os.path.splitext(caminho)[1].lower()
        if ext in (".xlsx", ".xls"):
            for aba in pd.ExcelFile(caminho).sheet_names:
                df_head = le_dataframe(caminho, nrows=5, sheet_name=aba)
                if df_head is None:
                    continue
                tipo = identifica_tipo(df_head.columns)
                if tipo != "desconhecido":
                    classificados.append({"caminho": caminho, "tipo": tipo, "aba": aba})
                    break
        else:
            df_head = le_dataframe(caminho, nrows=5)
            if df_head is not None:
                tipo = identifica_tipo(df_head.columns)
                if tipo != "desconhecido":
                    classificados.append({"caminho": caminho, "tipo": tipo, "aba": 0})
    except:
        pass
    progresso_da_etapa(idx, total_arquivos, 2, 18, f"Classificando ({idx}/{total_arquivos})")

arquivos_consumo    = [c["caminho"] for c in classificados if c["tipo"]=="consumo"]
arquivos_fatura     = [c["caminho"] for c in classificados if c["tipo"]=="fatura"]
arquivos_cronograma = [c["caminho"] for c in classificados if c["tipo"]=="cronograma"]

print(f"📁 Consumo: {len(arquivos_consumo)} | Fatura: {len(arquivos_fatura)} | Cronograma: {len(arquivos_cronograma)}")

faltando = [nome for nome, lista in (("FATURA", arquivos_fatura), ("CONSUMO", arquivos_consumo)) if not lista]
if faltando:
    raise FileNotFoundError(
        "Nenhum arquivo de " + " nem de ".join(faltando) + " foi identificado na pasta. "
        "Confira se os arquivos têm as colunas esperadas "
        f"(fatura: {sorted(COLUNAS_FATURA)}; consumo: {sorted(COLUNAS_CONSUMO)})."
    )

# ==================================================================
# ETAPA 2/6 — PROCESSAMENTO DE CADA GRUPO DE ARQUIVOS
# ==================================================================
print("="*70)
print("ETAPA 2/6 — PROCESSAMENTO DOS ARQUIVOS")
print("="*70)

def processa_lista_progresso(lista, func, ini, fin, desc):
    resultados = []
    total = len(lista)
    if total==0:
        atualiza_progresso(fin, desc)
        return resultados
    for i, c in enumerate(lista, start=1):
        resultados.append(func(c))
        progresso_da_etapa(i, total, ini, fin, f"{desc} ({i}/{total})")
    return resultados

consumos = processa_lista_progresso(arquivos_consumo, processa_consumo, 18,29,"Processando consumo")
consumo_total = pd.concat(consumos, ignore_index=True) if consumos else pd.DataFrame(columns=["N. Ligação_consumo","Referência"])
print(f"✅ Consumo: {len(consumo_total)} linhas")

faturas = processa_lista_progresso(arquivos_fatura, processa_fatura,29,40,"Processando faturas")
fatura_total = pd.concat(faturas, ignore_index=True) if faturas else pd.DataFrame(columns=["N. da Ligacao"])
print(f"✅ Fatura: {len(fatura_total)} linhas")

cronogramas = processa_lista_progresso(arquivos_cronograma, processa_cronograma,40,45,"Processando cronogramas")
cronograma_total = pd.concat(cronogramas, ignore_index=True).drop_duplicates(subset="Grupo", keep="last") if cronogramas else pd.DataFrame(columns=["Grupo","Data da Leitura","Qts. Dias","Aba/Mês Cronograma"])
print(f"✅ Cronogramas: {len(cronograma_total)} linhas")


# ==================================================================
# ETAPA 3/6 — MERGE (FATURA + CONSUMO + CRONOGRAMA) → BASE FINAL
# ==================================================================
print("="*70)
print("ETAPA 3/6 — MERGE")
print("="*70)

atualiza_progresso(47, "Merge base final")

colunas_conflito = ["Grupo", "Situacao Ligacao", "Nome Cliente", "Categoria"]
consumo_total = consumo_total.drop(columns=[c for c in colunas_conflito if c in consumo_total.columns], errors="ignore")

base_final = fatura_total.merge(
    consumo_total,
    left_on=["N. da Ligacao", "Referencia de Leitura"],
    right_on=["N. Ligação_consumo", "Referência"],
    how="left"
)
base_final["Encontrado no Consumo"] = base_final["N. Ligação_consumo"].notna().map({True:"Sim", False:"Não"})

base_final = base_final.merge(cronograma_total, on="Grupo", how="left")
base_final["Encontrado no Cronograma"] = base_final["Qts. Dias"].notna().map({True:"Sim", False:"Não"})

cols_excl = [c for c in base_final.columns if c.endswith("_consumo") or c.endswith("_cronograma")] + ["N. Ligação_consumo", "Referência"]
base_final = base_final.drop(columns=cols_excl, errors='ignore')
print(f"✅ Merge final: {len(base_final)} linhas")

base_final = base_final.rename(columns={
    "N. da Ligacao":"N. Ligação",
    "Valor Parcela":"Valor (R$)"
})
colunas_analise=["Total Economias","Qtd. Tipos de Economia","Economia Mista","Encontrado no Consumo","Encontrado no Cronograma"]
colunas_originais = [c for c in base_final.columns if c not in colunas_analise]
base_final = base_final[colunas_originais + colunas_analise]
atualiza_progresso(52, "Base final pronta")


# ==================================================================
# ETAPA 4/6 — EXPORTAÇÃO DA BASE CONSOLIDADA (XLSX)
# ==================================================================
print("="*70)
print("ETAPA 4/6 — EXPORTA")
print("="*70)
os.makedirs(os.path.dirname(CAMINHO_SAIDA), exist_ok=True)
base_final.to_excel(CAMINHO_SAIDA, index=False)
print(f"✅ Em: {CAMINHO_SAIDA}")

print(f"Linhas: {len(base_final)}")
print(f"Referências disponíveis: {sorted(base_final['Referencia de Leitura'].dropna().unique())}")
print(f"Match no consumo: {(base_final['Encontrado no Consumo']=='Sim').sum()}")
print(f"Sem match: {(base_final['Encontrado no Consumo']=='Não').sum()}")
print(f"Economia Mista: {(base_final['Economia Mista']=='Sim').sum()}")
print(f"Grupos com cronograma: {(base_final['Encontrado no Cronograma']=='Sim').sum()}")
atualiza_progresso(58, "Base exportada")

# ==================================================================
# ETAPA 5/6 — COMPARATIVOS (MÊS ATUAL x MÊS ANTERIOR)
# ==================================================================
print("="*70)
print("ETAPA 5/6 — COMPARATIVOS")
print("="*70)

def nome_mes(ref):
    m,a = ref.split("/")
    return f"{MESES_PT[int(m)-1]}/{a}"

REF_ATUAL = base_final["Referencia de Leitura"].dropna().max()
data_atual = pd.to_datetime(REF_ATUAL, format="%m/%Y")
REF_ANTERIOR = (data_atual - pd.DateOffset(months=1)).strftime("%m/%Y")
MES_ATUAL = nome_mes(REF_ATUAL)
MES_ANTERIOR = nome_mes(REF_ANTERIOR)
print(f"📅 {REF_ANTERIOR} ({MES_ANTERIOR}) vs {REF_ATUAL} ({MES_ATUAL})\n")

df_atual = base_final[base_final["Referencia de Leitura"] == REF_ATUAL].copy()
df_anterior = base_final[base_final["Referencia de Leitura"] == REF_ANTERIOR].copy()

def agrega_por_grupo(df, rubrica):
    filtro = df[df["Rubrica"].str.contains(rubrica, case=False, na=False)].copy()
    agrupado = filtro.groupby("Grupo").agg(
        **{
            "Dias_Leitura": ("Qts. Dias", "mean"),
            "Faturamento": ("Valor (R$)", "sum"),
            "Economias": ("N. Ligação", "nunique"),
            "Volume_Faturado": ("Consumo Faturado", "sum")
        }
    ).reset_index()
    agrupado["Volume_Medio"] = agrupado["Volume_Faturado"] / agrupado["Economias"].replace(0, np.nan)
    agrupado["Tarifa_Media"] = agrupado["Faturamento"] / agrupado["Volume_Faturado"].replace(0, np.nan)
    agrupado["Ticket_Medio"] = agrupado["Faturamento"] / agrupado["Economias"].replace(0, np.nan)
    return agrupado.fillna(0)

def monta_comparativo(df_at, df_ant, rubrica):
    at = agrega_por_grupo(df_at, rubrica)
    ant = agrega_por_grupo(df_ant, rubrica)
    comp = at.merge(ant, on="Grupo", how="outer", suffixes=("_atual","_anterior")).fillna(0)
    return comp.sort_values("Grupo").reset_index(drop=True)

print("📊 Comparando Água...")
comp_agua = monta_comparativo(df_atual, df_anterior, "AGUA")
print(f"   {len(comp_agua)} grupos")
print("📊 Comparando Esgoto...")
comp_esgoto = monta_comparativo(df_atual, df_anterior, "ESGOTO")
print(f"   {len(comp_esgoto)} grupos")
atualiza_progresso(68, "Comparativos")

# ------------------------------------------------------------------
# GERAÇÃO DA TABELA HTML DE COMPARATIVO (Água / Esgoto)
# ------------------------------------------------------------------
def fmt_num(v, dec=0):
    try:
        if dec==0:
            return f"{v:,.0f}".replace(",", ".")
        s = f"{v:,.{dec}f}"
        return s.replace(",", "§").replace(".", ",").replace("§", ".")
    except:
        return("0")

def fmt_moeda_br(v):
    """Formata número no padrão BR: 1.234.567,89"""
    try:
        s = f"{v:,.2f}"
        return s.replace(",", "§").replace(".", ",").replace("§", ".")
    except:
        return "0,00"

def fmt_int_br(v):
    """Formata número inteiro no padrão BR: 1.234.567"""
    try:
        return f"{v:,.0f}".replace(",", ".")
    except:
        return "0"

def gera_tabela(comp, titulo, slug):
    def td(campo, valor):
        return f'<td data-field="{campo}">{valor}</td>'
    def deltac(campo, valor, dec=2, pct=False):
        cor = "#c00000" if valor<0 else "#000"
        fundo = "#f9c9c9" if valor<0 else "transparent"
        txt = f"{valor*100:.1f}%".replace(".", ",") if pct else fmt_num(valor,dec)
        return f'<td data-field="{campo}" style="text-align:center; color:{cor}; background:{fundo};">{txt}</td>'
    def linha(grupo, d, is_media=False):
        delta_fat = d["Faturamento_atual"] - d["Faturamento_anterior"]
        delta_eco = d["Economias_atual"] - d["Economias_anterior"]
        delta_pct_eco = (delta_eco / d["Economias_anterior"]) if d["Economias_anterior"] else 0
        delta_vol = d["Volume_Faturado_atual"] - d["Volume_Faturado_anterior"]
        delta_pct_vol = (delta_vol / d["Volume_Faturado_anterior"]) if d["Volume_Faturado_anterior"] else 0
        delta_vm = d["Volume_Medio_atual"] - d["Volume_Medio_anterior"]
        delta_tar = d["Tarifa_Media_atual"] - d["Tarifa_Media_anterior"]
        delta_tic = d["Ticket_Medio_atual"] - d["Ticket_Medio_anterior"]
        g_attr = "" if is_media else html.escape(str(grupo), quote=True)
        classe = "linha-media" if is_media else ""
        attrs=""
        if not is_media:
            attrs = (
                f'data-dias-atual="{d["Dias_Leitura_atual"]}" data-dias-anterior="{d["Dias_Leitura_anterior"]}" '
                f'data-fat-atual="{d["Faturamento_atual"]}" data-fat-anterior="{d["Faturamento_anterior"]}" '
                f'data-eco-atual="{d["Economias_atual"]}" data-eco-anterior="{d["Economias_anterior"]}" '
                f'data-vol-atual="{d["Volume_Faturado_atual"]}" data-vol-anterior="{d["Volume_Faturado_anterior"]}"'
            )
        return f"""
        <tr class="{classe}" data-grupo="{g_attr}" {attrs}>
            {td("grupo", html.escape(str(grupo), quote=True))}
            {td("dias-atual", fmt_num(d["Dias_Leitura_atual"],1))}
            {td("dias-anterior", fmt_num(d["Dias_Leitura_anterior"],1))}
            {td("fat-atual", fmt_num(d["Faturamento_atual"]))}
            {td("fat-anterior", fmt_num(d["Faturamento_anterior"]))}
            {deltac("delta-fat", delta_fat)}
            {td("eco-atual", fmt_num(d["Economias_atual"]))}
            {td("eco-anterior", fmt_num(d["Economias_anterior"]))}
            {deltac("delta-pct-eco", delta_pct_eco, pct=True)}
            {deltac("delta-eco", delta_eco)}
            {td("vol-atual", fmt_num(d["Volume_Faturado_atual"]))}
            {td("vol-anterior", fmt_num(d["Volume_Faturado_anterior"]))}
            {deltac("delta-pct-vol", delta_pct_vol, pct=True)}
            {deltac("delta-vol", delta_vol)}
            {td("vm-atual", fmt_num(d["Volume_Medio_atual"],2))}
            {td("vm-anterior", fmt_num(d["Volume_Medio_anterior"],2))}
            {deltac("delta-vm", delta_vm)}
            {td("tar-atual", fmt_num(d["Tarifa_Media_atual"],2))}
            {td("tar-anterior", fmt_num(d["Tarifa_Media_anterior"],2))}
            {deltac("delta-tar", delta_tar)}
            {td("tic-atual", fmt_num(d["Ticket_Medio_atual"],2))}
            {td("tic-anterior", fmt_num(d["Ticket_Medio_anterior"],2))}
            {deltac("delta-tic", delta_tic)}
        </tr>
        """
    linhas_html = ""
    for _, r in comp.iterrows():
        linhas_html += linha(r["Grupo"], r)
    media = {
        "Dias_Leitura_atual": comp["Dias_Leitura_atual"].mean() if len(comp) else 0,
        "Dias_Leitura_anterior": comp["Dias_Leitura_anterior"].mean() if len(comp) else 0,
        "Faturamento_atual": comp["Faturamento_atual"].sum(),
        "Faturamento_anterior": comp["Faturamento_anterior"].sum(),
        "Economias_atual": comp["Economias_atual"].sum(),
        "Economias_anterior": comp["Economias_anterior"].sum(),
        "Volume_Faturado_atual": comp["Volume_Faturado_atual"].sum(),
        "Volume_Faturado_anterior": comp["Volume_Faturado_anterior"].sum(),
    }
    media["Volume_Medio_atual"] = (media["Volume_Faturado_atual"] / media["Economias_atual"]) if media["Economias_atual"] else 0
    media["Volume_Medio_anterior"] = (media["Volume_Faturado_anterior"] / media["Economias_anterior"]) if media["Economias_anterior"] else 0
    media["Tarifa_Media_atual"] = (media["Faturamento_atual"] / media["Volume_Faturado_atual"]) if media["Volume_Faturado_atual"] else 0
    media["Tarifa_Media_anterior"] = (media["Faturamento_anterior"] / media["Volume_Faturado_anterior"]) if media["Volume_Faturado_anterior"] else 0
    media["Ticket_Medio_atual"] = (media["Faturamento_atual"] / media["Economias_atual"]) if media["Economias_atual"] else 0
    media["Ticket_Medio_anterior"] = (media["Faturamento_anterior"] / media["Economias_anterior"]) if media["Economias_anterior"] else 0
    linhas_html += linha("Média", media, is_media=True)
    cabecalho=f"""
    <tr class="header-grupo">
        <th rowspan="2">Grupo</th>
        <th colspan="2">Dias Leitura</th>
        <th colspan="2">Faturamento</th>
        <th colspan="1">Δ Faturamento</th>
        <th colspan="2">Economias</th>
        <th colspan="2">Δ Economias</th>
        <th colspan="2">Volume Faturado</th>
        <th colspan="2">Δ Volume</th>
        <th colspan="2">Volume Médio</th>
        <th colspan="1">Δ Volume Médio</th>
        <th colspan="2">Tarifa Média</th>
        <th colspan="1">Δ Tarifa</th>
        <th colspan="2">Ticket Médio</th>
        <th colspan="1">Δ Ticket Médio</th>
    </tr>
    <tr class="header-sub">
        <th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th>
        <th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th>
        <th></th>
        <th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th>
        <th>%</th><th>Abs</th>
        <th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th>
        <th>%</th><th>Abs</th>
        <th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th>
        <th></th>
        <th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th>
        <th></th>
        <th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th>
        <th></th>
    </tr>
    """
    return f"""
    <div class="card">
    <h2>Comparativo {titulo}</h2>
    <table class="tabela-comparativo" id="tabela-{slug}">
        <thead>{cabecalho}</thead>
        <tbody>{linhas_html}</tbody>
    </table>
    </div>
    """

# ------------------------------------------------------------------
# QUADRO DE CICLOS — ATIVA x CORTADA
# ------------------------------------------------------------------
def monta_quadro_ciclos_situacao():
    print("📊 Montando quadro ciclos (Ativa x Cortada)...")
    df = base_final.copy()
    if "Situacao Ligacao" not in df.columns:
        return "<div class='card'><h2>Ciclos (Ativa x Cortada)</h2><p>Coluna 'Situacao Ligacao' não encontrada</p></div>"
    df["Situacao Ligacao"] = df["Situacao Ligacao"].astype(str).str.upper()
    def norm_sit(s):
        if "ATIV" in s: return "Ativa"
        elif "CORT" in s: return "Cortada"
        return None
    df["Situacao_Norm"] = df["Situacao Ligacao"].apply(norm_sit)
    df = df[df["Situacao_Norm"].notna()]
    def conta_por(referencia, sit):
        return df[(df["Referencia de Leitura"]==referencia) & (df["Situacao_Norm"]==sit)].groupby("Grupo")["N. Ligação"].nunique()
    aa = conta_por(REF_ATUAL, "Ativa")
    ac = conta_por(REF_ATUAL, "Cortada")
    aa2 = conta_por(REF_ANTERIOR, "Ativa")
    ac2 = conta_por(REF_ANTERIOR, "Cortada")
    grupos = sorted(set(aa.index) | set(ac.index) | set(aa2.index) | set(ac2.index))
    linhas=[]
    for g in grupos:
        aa_g=int(aa.get(g,0))
        ac_g=int(ac.get(g,0))
        aa2_g=int(aa2.get(g,0))
        ac2_g=int(ac2.get(g,0))
        linhas.append({
            "Grupo": html.escape(str(g), quote=True),
            "Ativa_Atual": aa_g,
            "Cortada_Atual": ac_g,
            "Ativa_Ant": aa2_g,
            "Cortada_Ant": ac2_g,
            "Dif_Ativas": aa_g - aa2_g,
            "Dif_Cortadas": ac_g - ac2_g
        })
    df_ciclo=pd.DataFrame(linhas)
    if df_ciclo.empty:
        return "<div class='card'><h2>Ciclos (Ativa x Cortada)</h2><p>Sem dados</p></div>"
    total_ativa = df_ciclo["Ativa_Atual"].sum()
    total_cort = df_ciclo["Cortada_Atual"].sum()
    total_ant_ativa = df_ciclo["Ativa_Ant"].sum()
    total_ant_cort = df_ciclo["Cortada_Ant"].sum()
    total_dif_ativa = total_ativa - total_ant_ativa
    total_dif_cort = total_cort - total_ant_cort
    def fmt(v): return f"{v:,.0f}".replace(",",".")
    linhas_html = ""
    for _, r in df_ciclo.iterrows():
        cor_dif_ativa = "#c00000" if r["Dif_Ativas"]<0 else "#000"
        cor_dif_cort = "#c00000" if r["Dif_Cortadas"]<0 else "#000"
        linhas_html += f"""
        <tr>
            <td style="text-align:center;">{r['Grupo']}</td>
            <td style="text-align:center;">{fmt(r['Ativa_Atual'])}</td>
            <td style="text-align:center;">{fmt(r['Ativa_Ant'])}</td>
            <td style="text-align:center;">{fmt(r['Cortada_Atual'])}</td>
            <td style="text-align:center;">{fmt(r['Cortada_Ant'])}</td>
            <td style="text-align:center; color:{cor_dif_ativa};">{fmt(r['Dif_Ativas'])}</td>
            <td style="text-align:center; color:{cor_dif_cort};">{fmt(r['Dif_Cortadas'])}</td>
        </tr>
        """
    cor_total_ativa = "#c00000" if total_dif_ativa<0 else "#000"
    cor_total_cort = "#c00000" if total_dif_cort<0 else "#000"
    linhas_html += f"""
    <tr class="linha-total">
        <td style="text-align:center;">Total</td>
        <td style="text-align:center;">{fmt(total_ativa)}</td>
        <td style="text-align:center;">{fmt(total_ant_ativa)}</td>
        <td style="text-align:center;">{fmt(total_cort)}</td>
        <td style="text-align:center;">{fmt(total_ant_cort)}</td>
        <td style="text-align:center; color:{cor_total_ativa};">{fmt(total_dif_ativa)}</td>
        <td style="text-align:center; color:{cor_total_cort};">{fmt(total_dif_cort)}</td>
    </tr>
    """
    cab = f"""
    <tr class="header-grupo">
        <th rowspan="2">Ciclos</th>
        <th colspan="2">A-Ativa</th>
        <th colspan="2">C-Cortada</th>
        <th rowspan="2">Diferença</th>
    </tr>
    <tr class="header-sub">
        <th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th><th>{MES_ATUAL}</th><th>{MES_ANTERIOR}</th><th></th>
    </tr>
    """
    return f"""
    <div class="card">
    <h2>Economias Faturadas por Ciclo — Ativa x Cortada</h2>
    <table>{cab}{linhas_html}</table>
    </div>
    """

quadro_ciclos_html = monta_quadro_ciclos_situacao()
atualiza_progresso(78, "Ciclos ativo/cortada finalizado")

# ==================================================================
# TOP 100 CLIENTES COM MAIOR QUEDA DE CONSUMO
# ==================================================================
def gera_top100_quedas(df_at, df_ant, rubrica, ref_at, ref_ant):
    def prepara(df):
        df=df.copy()
        df["N. Ligação"]=df["N. Ligação"].astype(str).str.strip()
        df["Nome_Cliente"] = df.get("Nome Cliente", pd.Series(dtype=str)).astype(str).str.strip()
        df["Grupo"] = df.get("Grupo", pd.Series(dtype=str)).astype(str).str.strip()
        df["Categoria"] = df.get("Categoria", pd.Series(dtype=str)).astype(str).str.strip()
        df["Consumo_Num"] = pd.to_numeric(df.get("Consumo Faturado", 0), errors="coerce").fillna(0)
        df["Valor_Num"] = pd.to_numeric(df.get("Valor (R$)", 0), errors="coerce").fillna(0)
        return df
    at = prepara(df_at[df_at["Rubrica"].str.contains(rubrica, case=False, na=False)])
    ant = prepara(df_ant[df_ant["Rubrica"].str.contains(rubrica, case=False, na=False)])
    at_group = at.groupby("N. Ligação").agg(
        **{
            "Nome_Cliente": ("Nome_Cliente", "first"),
            "Grupo": ("Grupo", "first"),
            "Categoria": ("Categoria", "first"),
            "Consumo_Atual": ("Consumo_Num", "sum"),
            "Valor_Atual": ("Valor_Num", "sum"),
        }
    ).reset_index()
    ant_group = ant.groupby("N. Ligação").agg(
        **{
            "Consumo_Anterior": ("Consumo_Num", "sum"),
            "Valor_Anterior": ("Valor_Num", "sum")
        }
    ).reset_index()

    comp = at_group.merge(ant_group, on="N. Ligação", how="inner")
    comp["Queda_Consumo"] = comp["Consumo_Anterior"] - comp["Consumo_Atual"]
    comp["Queda_%"] = np.where(comp["Consumo_Anterior"] > 0, comp["Queda_Consumo"] / comp["Consumo_Anterior"] * 100, 0)
    comp["Queda_Valor_R$"] = comp["Valor_Anterior"] - comp["Valor_Atual"]
    comp = comp[comp["Queda_Consumo"] > 0]
    comp = comp.sort_values("Queda_Consumo", ascending=False).head(100)
    comp["Ranking"] = range(1, len(comp) + 1)
    col_nome_at = f"Consumo {ref_at}"
    col_nome_ant = f"Consumo {ref_ant}"
    col_valor_at = f"Valor R$ {ref_at}"
    col_valor_ant = f"Valor R$ {ref_ant}"
    comp = comp.rename(columns={
        "Consumo_Atual": col_nome_at,
        "Consumo_Anterior": col_nome_ant,
        "Valor_Atual": col_valor_at,
        "Valor_Anterior": col_valor_ant,
    })
    return comp[["Ranking","N. Ligação","Nome_Cliente","Grupo","Categoria",
        col_nome_at,col_nome_ant,"Queda_Consumo","Queda_%",col_valor_at,col_valor_ant,"Queda_Valor_R$"]]

def exporta_top100(df_at, df_ant, ref_at, ref_ant):
    print("🏆 Top 100 clientes com maior queda")
    top_agua = gera_top100_quedas(df_at, df_ant, "AGUA", ref_at, ref_ant)
    top_esg = gera_top100_quedas(df_at, df_ant, "ESGOTO", ref_at, ref_ant)
    os.makedirs(os.path.dirname(CAMINHO_SAIDA_TOP100), exist_ok=True)
    with pd.ExcelWriter(CAMINHO_SAIDA_TOP100, engine="openpyxl") as w:
        top_agua.to_excel(w, sheet_name="Top100_Agua", index=False)
        top_esg.to_excel(w, sheet_name="Top100_Esgoto", index=False)
    print(f"✅ Top100 em: {CAMINHO_SAIDA_TOP100}")
    return top_agua, top_esg

# ==================================================================
# GERAÇÃO DE INSIGHTS E KPIs AUTOMÁTICOS
# ==================================================================
def gera_resumo_insights(base_final, comp_agua, comp_esgoto, ref_at, ref_ant, mes_at, mes_ant, top_agua, top_esg):
    """Gera insights textuais e um resumo de KPIs, com visual e conteúdo renovados."""
    print("🧠 Insights do mês")
    linhas=[]
    def add(cat, txt): linhas.append({"Categoria":cat, "Insight":txt})
    def fmtmoeda(v): return f"{v:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
    def fmtint(v): return f"{v:,.0f}".replace(",", ".")

    def kpi(c): return {
        "fat": c["Faturamento_atual"].sum() if len(c) else 0,
        "fat_ant": c["Faturamento_anterior"].sum() if len(c) else 0,
        "eco": c["Economias_atual"].sum() if len(c) else 0,
        "eco_ant": c["Economias_anterior"].sum() if len(c) else 0,
        "vol": c["Volume_Faturado_atual"].sum() if len(c) else 0,
        "vol_ant": c["Volume_Faturado_anterior"].sum() if len(c) else 0
    }
    ka = kpi(comp_agua)
    ke = kpi(comp_esgoto)

    fat_total_at = ka["fat"] + ke["fat"]
    fat_total_ant = ka["fat_ant"] + ke["fat_ant"]
    delta_fat = fat_total_at - fat_total_ant
    pct_fat = (delta_fat / fat_total_ant *100) if fat_total_ant else 0
    add("Faturamento (Total)", f"Total R$ {fmtmoeda(fat_total_at)} ({'+' if delta_fat>=0 else ''}{pct_fat:.1f}%)")

    for nome, k in [("Água", ka), ("Esgoto", ke)]:
        delta_f = k["fat"] - k["fat_ant"]
        delta_v = k["vol"] - k["vol_ant"]
        delta_e = k["eco"] - k["eco_ant"]
        pctf = (delta_f / k["fat_ant"]*100) if k["fat_ant"] else 0
        pctv = (delta_v / k["vol_ant"]*100) if k["vol_ant"] else 0
        add(nome, f"Faturamento {'cresceu' if delta_f>=0 else 'caiu'} {abs(pctf):.1f}% (R$ {fmtmoeda(delta_f)})")
        add(nome, f"Volume faturado {'cresceu' if delta_v>=0 else 'caiu'} {abs(pctv):.1f}% ({fmtint(delta_v)} m³)")
        # Economias que caíram, em valor absoluto (não percentual)
        if delta_e < 0:
            add(nome, f"Economias faturadas caíram {fmtint(abs(delta_e))} ligações (queda absoluta)")
        elif delta_e > 0:
            add(nome, f"Economias faturadas cresceram {fmtint(delta_e)} ligações")
        else:
            add(nome, "Sem variação no número de economias faturadas")

    def top_var(c, nome, n=3):
        c = c.copy()
        c["Delta"] = c["Faturamento_atual"] - c["Faturamento_anterior"]
        piores = c.sort_values("Delta").head(n)
        melhores = c.sort_values("Delta", ascending=False).head(n)
        for _, r in piores.iterrows():
            if r["Delta"] < 0:
                add(f"Queda - {nome}", f"Grupo {r['Grupo']}: faturamento R$ {fmtmoeda(abs(r['Delta']))} abaixo")
        for _, r in melhores.iterrows():
            if r["Delta"] > 0:
                add(f"Crescimento - {nome}", f"Grupo {r['Grupo']}: faturamento R$ {fmtmoeda(r['Delta'])} acima")
    top_var(comp_agua, "Água")
    top_var(comp_esgoto, "Esgoto")

    # Cortes: agora traz também as ATIVAS
    if "Situacao Ligacao" in base_final.columns:
        sit = base_final["Situacao Ligacao"].astype(str).str.upper()
        cort_at = base_final[(base_final["Referencia de Leitura"]==ref_at) & sit.str.contains("CORT")]["N. Ligação"].nunique()
        cort_ant = base_final[(base_final["Referencia de Leitura"]==ref_ant) & sit.str.contains("CORT")]["N. Ligação"].nunique()
        ativa_at = base_final[(base_final["Referencia de Leitura"]==ref_at) & sit.str.contains("ATIV")]["N. Ligação"].nunique()
        ativa_ant = base_final[(base_final["Referencia de Leitura"]==ref_ant) & sit.str.contains("ATIV")]["N. Ligação"].nunique()
    else:
        cort_at, cort_ant, ativa_at, ativa_ant = 0,0,0,0
    add("Cortes", f"{fmtint(cort_at)} ligações cortadas ({cort_at - cort_ant:+d} vs {mes_ant})")
    add("Cortes", f"{fmtint(ativa_at)} ligações ativas ({ativa_at - ativa_ant:+d} vs {mes_ant})")

    # Variação absoluta de ligações faturando
    lig_at = base_final[base_final["Referencia de Leitura"]==ref_at]["N. Ligação"].nunique()
    lig_ant = base_final[base_final["Referencia de Leitura"]==ref_ant]["N. Ligação"].nunique()
    delta_lig = lig_at - lig_ant
    add("Ligações Faturando", f"{fmtint(lig_at)} ligações faturando ({delta_lig:+d} vs {mes_ant})")

    # Top100: 2 maiores quedas (Água e Esgoto)
    for nome, top in [("Água", top_agua), ("Esgoto", top_esg)]:
        if len(top) >= 1:
            r1 = top.iloc[0]
            add(f"Top100 {nome}", f"1ª maior queda: {r1['N. Ligação']} ({r1['Grupo']}) — {r1['Queda_Consumo']:.0f} m³")
        if len(top) >= 2:
            r2 = top.iloc[1]
            add(f"Top100 {nome}", f"2ª maior queda: {r2['N. Ligação']} ({r2['Grupo']}) — {r2['Queda_Consumo']:.0f} m³")
        add(f"Top100 {nome}", f"Total de clientes com queda: {len(top)}")

    df_ins = pd.DataFrame(linhas)
    df_kpi = pd.DataFrame([
        {"Indicador":"Faturamento Água", f"{mes_ant}": ka["fat_ant"], f"{mes_at}": ka["fat"]},
        {"Indicador":"Faturamento Esgoto", f"{mes_ant}": ke["fat_ant"], f"{mes_at}": ke["fat"]}
    ])
    return df_kpi, df_ins

top_agua, top_esg = exporta_top100(df_atual, df_anterior, REF_ATUAL, REF_ANTERIOR)
df_kpis, df_insights = gera_resumo_insights(base_final, comp_agua, comp_esgoto, REF_ATUAL, REF_ANTERIOR, MES_ATUAL, MES_ANTERIOR, top_agua, top_esg)
atualiza_progresso(94, "Top 100 e Insights finalizados")

# ==================================================================
# CARDS DE KPIs, INSIGHTS E TABELA TOP100 PARA O RELATÓRIO HTML
# ==================================================================
def gera_cards_kpis(df_kpis, comp_agua, comp_esgoto, mes_atual, mes_anterior):
    """Gera os cartões HTML de KPIs principais + gráfico de faturamento por grupo + obs de dias de leitura."""
    cards = ""
    icones = {"Faturamento Água": "💧", "Faturamento Esgoto": "🚿"}
    for _, r in df_kpis.iterrows():
        colunas = [c for c in df_kpis.columns if c != "Indicador"]
        v_ant, v_at = r[colunas[0]], r[colunas[1]]
        delta = v_at - v_ant
        pct = (delta / v_ant * 100) if v_ant else 0
        cor = "#c00000" if delta < 0 else "#1e8449"
        seta = "▼" if delta < 0 else "▲"
        icone = icones.get(r["Indicador"], "📊")
        cards += f"""
        <div class="kpi-card">
            <div class="kpi-icone">{icone}</div>
            <h3>{r['Indicador']}</h3>
            <p class="kpi-valor">R$ {fmt_moeda_br(v_at)}</p>
            <p class="kpi-delta" style="color:{cor};">{seta} {abs(pct):.1f}% vs mês anterior</p>
        </div>
        """

    # ---- Dados para o gráfico (Faturamento Bruto por Grupo, mês a mês) ----
    comp_total = pd.concat([
        comp_agua[["Grupo", "Faturamento_atual", "Faturamento_anterior"]],
        comp_esgoto[["Grupo", "Faturamento_atual", "Faturamento_anterior"]]
    ]).groupby("Grupo", as_index=False).sum().sort_values("Grupo")

    grupos_lbl = [str(g) for g in comp_total["Grupo"].tolist()]
    vals_atual = [round(float(v), 2) for v in comp_total["Faturamento_atual"].tolist()]
    vals_anterior = [round(float(v), 2) for v in comp_total["Faturamento_anterior"].tolist()]

    # ---- Média de dias de leitura por mês ----
    media_dias_atual = pd.concat([comp_agua["Dias_Leitura_atual"], comp_esgoto["Dias_Leitura_atual"]]).mean()
    media_dias_anterior = pd.concat([comp_agua["Dias_Leitura_anterior"], comp_esgoto["Dias_Leitura_anterior"]]).mean()
    media_dias_atual = 0 if pd.isna(media_dias_atual) else media_dias_atual
    media_dias_anterior = 0 if pd.isna(media_dias_anterior) else media_dias_anterior

    grafico_html = f"""
    <div class="card">
        <h2>📊 Faturamento Bruto por Grupo de Leitura — {mes_atual} vs {mes_anterior}</h2>
        <canvas id="graficoFaturamento" height="90"></canvas>
        <p class="obs-dias">
            📅 <b>Média de dias de leitura:</b>
            {mes_atual}: {media_dias_atual:.1f} dias &nbsp;|&nbsp;
            {mes_anterior}: {media_dias_anterior:.1f} dias
        </p>
    </div>
    <script>
    (function() {{
        const ctx = document.getElementById('graficoFaturamento').getContext('2d');
        new Chart(ctx, {{
            type: 'bar',
            data: {{
                labels: {grupos_lbl},
                datasets: [
                    {{
                        label: '{mes_anterior}',
                        data: {vals_anterior},
                        backgroundColor: '#9fb8cc'
                    }},
                    {{
                        label: '{mes_atual}',
                        data: {vals_atual},
                        backgroundColor: '#14375e'
                    }}
                ]
            }},
            options: {{
                responsive: true,
                plugins: {{
                    legend: {{ position: 'top' }},
                    tooltip: {{
                        callbacks: {{
                            label: function(ctx) {{
                                let v = ctx.raw.toLocaleString('pt-BR', {{minimumFractionDigits:2, maximumFractionDigits:2}});
                                return ctx.dataset.label + ': R$ ' + v;
                            }}
                        }}
                    }}
                }},
                scales: {{
                    y: {{
                        ticks: {{
                            callback: function(value) {{ return value.toLocaleString('pt-BR'); }}
                        }}
                    }}
                }}
            }}
        }});
    }})();
    </script>
    """

    return cards, grafico_html

def gera_cards_insights(df_insights):
    """
    Gera os cartões HTML com os insights textuais, organizados em SEÇÕES:
    Faturamento Total, Água, Esgoto, Ligações Faturando, e Outros Indicadores.
    """
    ordem_secoes = [
        ("Faturamento (Total)", "💰 Faturamento Total"),
        ("Água", "💧 Água"),
        ("Esgoto", "🚿 Esgoto"),
        ("Ligações Faturando", "🔌 Ligações Faturando"),
    ]

    categorias_usadas = set()
    html_secoes = ""

    for chave, titulo in ordem_secoes:
        grupo = df_insights[df_insights["Categoria"] == chave]
        categorias_usadas.add(chave)
        if grupo.empty:
            continue
        itens = "".join([f"<li>{html.escape(t)}</li>" for t in grupo["Insight"]])
        html_secoes += f"""
        <div class="insights-secao">
            <h3>{titulo}</h3>
            <div class="insights-grid">
                <div class="insight-card"><ul>{itens}</ul></div>
            </div>
        </div>
        """

    outras_categorias = [c for c in df_insights["Categoria"].unique() if c not in categorias_usadas]
    if outras_categorias:
        cards_outros = ""
        for cat in sorted(outras_categorias):
            grupo = df_insights[df_insights["Categoria"] == cat]
            itens = "".join([f"<li>{html.escape(t)}</li>" for t in grupo["Insight"]])
            cards_outros += f"""
            <div class="insight-card">
                <h4>{html.escape(cat)}</h4>
                <ul>{itens}</ul>
            </div>
            """
        html_secoes += f"""
        <div class="insights-secao">
            <h3>📌 Outros Indicadores</h3>
            <div class="insights-grid">{cards_outros}</div>
        </div>
        """

    return html_secoes

def gera_tabela_top100(df, titulo):
    if df.empty:
        return f"<div class='card'><h2>{titulo}</h2><p>Sem dados</p></div>"

    df_show = df.copy()

    def fmt_valor(col, v):
        if pd.isna(v):
            return ""
        if col == "Queda_%":
            return f"{v:.1f}%".replace(".", ",")
        if isinstance(v, (int, float, np.floating, np.integer)):
            if col.startswith("Valor R$") or col == "Queda_Valor_R$":
                return f"{v:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
            if col.startswith("Consumo") or col == "Queda_Consumo":
                return f"{v:,.0f}".replace(",", ".")
            return str(v)
        return str(v)

    linhas_html = ""
    for _, r in df_show.iterrows():
        linhas_html += "<tr>" + "".join(
            f"<td>{html.escape(fmt_valor(c, r[c]))}</td>" for c in df_show.columns
        ) + "</tr>"

    colunas_html = "".join(f"<th>{html.escape(str(c))}</th>" for c in df_show.columns)
    return f"""
    <div class="card">
    <h2>{titulo}</h2>
    <table class="tabela-top100">
        <thead><tr>{colunas_html}</tr></thead>
        <tbody>{linhas_html}</tbody>
    </table>
    </div>
    """

cards_kpis_html, grafico_faturamento_html = gera_cards_kpis(df_kpis, comp_agua, comp_esgoto, MES_ATUAL, MES_ANTERIOR)
cards_insights_html = gera_cards_insights(df_insights)
tabela_top100_agua_html = gera_tabela_top100(top_agua, "Top 100 — Maiores Quedas de Consumo (Água)")
tabela_top100_esgoto_html = gera_tabela_top100(top_esg, "Top 100 — Maiores Quedas de Consumo (Esgoto)")
matriz_html = ""

# ==================================================================
# ETAPA 6/6 — GERAÇÃO DO RELATÓRIO HTML FINAL (com abas e filtros)
# ==================================================================
print("="*70)
print("ETAPA 6/6 — GERAÇÃO HTML COM ABAS")
print("="*70)

grupos_disponiveis = (
    fatura_total["Grupo"]
    .dropna()
    .astype(str).str.strip()
    .unique()
)
grupos_disponiveis = sorted([g for g in grupos_disponiveis if g not in ("nan","None","")])

checkboxes_html = ""
for g in grupos_disponiveis:
    check=html.escape(g,quote=True)
    checkboxes_html += f"<label class='check-item'><input class='chk-grupo' type='checkbox' value='{check}' checked onchange='filtrarPorGrupo()'><span>{html.escape(g)}</span></label>"

filtro_html = f"""
<div class="filtro-wrap">
<button id="btnFiltro" class="btn-filtro" onclick="toggleFiltro(event)">
    <span>🔎 Filtrar Ciclo/Grupo</span>
    <span id="badgeFiltro" class="badge">{len(grupos_disponiveis)}</span>
</button>
<div id="painelFiltro" class="painel-filtro">
<div class="painel-acoes">
<button class="mini-btn" onclick="marcarTodos(true)">Marcar todos</button>
<button class="mini-btn" onclick="marcarTodos(false)">Limpar</button>
</div>
<div class="check-list">{checkboxes_html}</div>
</div>
</div>
"""

# ------------------------------------------------------------------
# ESTILO VISUAL (Cabeçalho "Águas do Rio", tabelas e KPIs renovados)
# ------------------------------------------------------------------
html_style = """
<style>
* { box-sizing: border-box; }
body { font-family:'Segoe UI', Arial, sans-serif; background:#f4f6f9; margin:0; }

/* ===== CABEÇALHO ===== */
.header-exec {
    background: linear-gradient(135deg, #0b2447 0%, #14375e 60%, #1b4a76 100%);
    padding: 28px 32px;
    color: #fff;
}
.header-badge {
    display: inline-block;
    background: rgba(255,255,255,0.12);
    border: 1px solid rgba(255,255,255,0.25);
    color: #5ee7c8;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    padding: 5px 14px;
    border-radius: 20px;
    margin-bottom: 14px;
}
.header-exec h1 {
    font-size: 1.9em;
    font-weight: 800;
    margin: 0 0 6px 0;
    line-height: 1.2;
}
.header-exec p {
    font-size: 0.9em;
    color: #cbd5e1;
    margin: 0;
}

/* ===== ABAS ===== */
#view-resumo, #view-tabelas { display:none; }
#view-resumo.ativo, #view-tabelas.ativo { display:block; }
.toggle { display:flex; justify-content:center; margin:16px 0; }
.toggle button { padding:8px 18px; border:none; border-radius:5px; background:#14375e; color:#fff; margin:0 4px; cursor:pointer; font-weight:600; font-size:0.85em; }
.toggle button.active { background:#1b9e82; }

/* ===== CARDS ===== */
.card { background:#fff; margin:16px auto; padding:16px; max-width:1300px; border-radius:8px; box-shadow:0 2px 6px rgba(0,0,0,0.1); overflow-x:auto; }
.card h2 { font-size:1.05em; margin:0 0 12px 0; color:#14375e; }

/* ===== KPIs (visual renovado, menores) ===== */
.kpis-grid { display:flex; flex-wrap:wrap; gap:16px; justify-content:center; margin:20px 16px; }
.kpi-card {
    background:#fff; padding:14px 18px; border-radius:14px; min-width:180px;
    text-align:center; box-shadow:0 4px 14px rgba(20,55,94,0.08);
    border-top: 4px solid #1b9e82; transition: transform .15s;
}
.kpi-card:hover { transform: translateY(-3px); }
.kpi-icone { font-size:1.3em; margin-bottom:4px; }
.kpi-card h3 { font-size:0.7em; color:#556; margin:0 0 6px 0; font-weight:700; text-transform:uppercase; letter-spacing:.03em; }
.kpi-valor { font-size:1.05em; font-weight:800; margin:2px 0; color:#0b2447; }
.kpi-delta { font-size:0.72em; margin:4px 0 0 0; font-weight:700; }

/* ===== OBSERVAÇÃO DIAS DE LEITURA ===== */
.obs-dias { font-size:0.82em; color:#444; margin-top:10px; text-align:center; }

/* ===== INSIGHTS (blocos separados, mais elegantes) ===== */
.insights-secao { margin-bottom: 22px; }
.insights-secao h3 {
    font-size: 1em;
    color: #fff;
    background: linear-gradient(90deg, #14375e, #1b6f8f);
    display:inline-block;
    padding: 6px 16px;
    border-radius: 20px;
    margin: 0 0 12px 0;
    font-weight: 700;
}
.insights-grid { display:flex; flex-wrap:wrap; gap:14px; }
.insight-card {
    background:#fafcff; border:1px solid #e6ebf1; border-radius:10px;
    padding:14px 18px; flex:1 1 300px; box-shadow:0 2px 6px rgba(0,0,0,0.03);
}
.insight-card h4 { font-size:0.82em; margin:0 0 8px 0; color:#14375e; font-weight:700; }
.insight-card ul { margin:0; padding-left:18px; font-size:0.82em; color:#333; line-height:1.6; }
.insight-card li { margin-bottom:5px; }
.insight-card li::marker { color:#1b9e82; }

/* ===== TABELAS (fonte reduzida) ===== */
table { border-collapse:collapse; width:100%; font-size:0.62em; }
th, td { border:1px solid #ddd; padding:3px 5px; text-align:center; }
th { background:#14375e; color:#fff; font-size:0.85em; }
.linha-media, .linha-total { font-weight:700; background:#eef2f7; }

/* ===== FILTRO (dropdown flutuante, alinhado com as tabelas) ===== */
.filtro-wrap { margin:16px auto; max-width:1300px; position:relative; }
.btn-filtro { padding:8px 14px; border-radius:6px; border:none; background:#14375e; color:#fff; cursor:pointer; font-size:0.85em; }
.painel-filtro {
    display:none;
    position:absolute;
    top:calc(100% + 4px);
    left:0;
    z-index:100;
    background:#fff;
    border:1px solid #ddd;
    border-radius:6px;
    padding:12px;
    max-height:320px;
    overflow-y:auto;
    box-shadow:0 6px 18px rgba(0,0,0,0.15);
    min-width:260px;
}
.check-item { display:block; margin:4px 0; font-size:0.85em; }
.mini-btn { margin-right:8px; padding:4px 10px; border:none; border-radius:4px; background:#ccc; cursor:pointer; font-size:0.8em; }
.badge { background:#1b9e82; color:#fff; border-radius:10px; padding:1px 8px; font-size:0.75em; margin-left:6px; }
</style>
"""

script_js = """
<script>
function mostrarView(view) {
    document.querySelectorAll('#view-resumo, #view-tabelas').forEach(e => e.classList.remove('ativo'));
    document.getElementById('view-'+view).classList.add('ativo');
    document.querySelectorAll('.toggle button').forEach(btn=>btn.classList.remove('active'));
    document.getElementById('btn-'+view).classList.add('active');
}
function toggleFiltro(evt) {
    if (evt) evt.stopPropagation();
    const painel = document.getElementById('painelFiltro');
    painel.style.display = (painel.style.display === 'block') ? 'none' : 'block';
}
document.addEventListener('click', function(e) {
    const wrap = document.querySelector('.filtro-wrap');
    const painel = document.getElementById('painelFiltro');
    if (wrap && painel && !wrap.contains(e.target)) {
        painel.style.display = 'none';
    }
});
function marcarTodos(valor) {
    document.querySelectorAll('.chk-grupo').forEach(chk => chk.checked = valor);
    filtrarPorGrupo();
}
function filtrarPorGrupo() {
    const marcados = Array.from(document.querySelectorAll('.chk-grupo:checked')).map(c => c.value);
    document.getElementById('badgeFiltro').innerText = marcados.length;
    document.querySelectorAll('tr[data-grupo]').forEach(tr => {
        const g = tr.getAttribute('data-grupo');
        if (g === '') return;
        tr.style.display = marcados.includes(g) ? '' : 'none';
    });
}
</script>
"""

# ------------------------------------------------------------------
# MONTAGEM FINAL DO HTML (Cabeçalho + Resumo + Tabelas)
# ------------------------------------------------------------------
html_final = f"""
<!DOCTYPE html>
<html lang='pt-br'>
<head>
<meta charset='UTF-8'/>
<title>Relatório Águas e Esgoto</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{html_style}
</head>
<body>

<div class="header-exec">
    <div class="header-badge">Águas do Rio · Relatório Executivo</div>
    <h1>Comparativo de Água e Esgoto — {MES_ATUAL} vs {MES_ANTERIOR}</h1>
    <p>Faturamento, economias, volumes e migração de ciclo consolidados automaticamente</p>
</div>

<div class='toggle'>
<button id='btn-resumo' class='active' onclick='mostrarView("resumo")'>📈 Ver Resumo</button>
<button id='btn-tabelas' onclick='mostrarView("tabelas")'>📋 Ver Tabelas</button>
</div>
<div id='view-resumo' class='ativo'>
<div class='kpis-grid'>{cards_kpis_html}</div>
{grafico_faturamento_html}
<div class='card'><h2>💡 Insights do mês {MES_ATUAL}</h2>{cards_insights_html}</div>
</div>
<div id='view-tabelas'>
{filtro_html}
{gera_tabela(comp_agua, "Água", "agua")}
{gera_tabela(comp_esgoto, "Esgoto", "esgoto")}
{quadro_ciclos_html}
{matriz_html}
{tabela_top100_agua_html}
{tabela_top100_esgoto_html}
</div>
{script_js}
</body>
</html>
"""

os.makedirs(os.path.dirname(CAMINHO_SAIDA_HTML), exist_ok=True)
with open(CAMINHO_SAIDA_HTML, "w", encoding="utf-8") as f:
    f.write(html_final)

atualiza_progresso(100, "Finalizado")
barra_progresso.close()

print(f"Relatório gerado em: {CAMINHO_SAIDA_HTML}")

# ------------------------------------------------------------------
# DOWNLOAD AUTOMÁTICO DOS RESULTADOS (modo upload no Colab)
# ------------------------------------------------------------------
if em_colab() and MODO_ORIGEM == "upload":
    from google.colab import files
    for saida in (CAMINHO_SAIDA_HTML, CAMINHO_SAIDA, CAMINHO_SAIDA_TOP100):
        if os.path.exists(saida):
            files.download(saida)